// Fallback versions if auto-detection fails
export const MINECRAFT_VERSIONS = [
  '1.21.4',
  '1.20.1',
  '1.19.2',
  '1.18.2',
  '1.16.5'
];

export const GITHUB_API_BASE = 'https://api.github.com';

export const SYSTEM_INSTRUCTION = `You are an expert Minecraft Mod Developer specializing in both Forge and Fabric loaders.
Your goal is to assist users in writing Java code for Minecraft mods, debugging errors, and configuring build scripts (Gradle).
You have access to the project file structure and can suggest file creations or edits.
When providing code, prefer modern Java practices appropriate for the selected Minecraft version.
`;

// Standard gradlew script (Unix)
export const GRADLEW_SCRIPT = `#!/bin/sh
DIR=$(dirname "$0")
command -v gradle >/dev/null 2>&1 || { echo >&2 "Gradle is not installed. Please install Gradle."; exit 1; }
gradle "$@"
`;

export const SETTINGS_GRADLE = `pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}
rootProject.name = 'modid'
`;

// Updated to ForgeGradle 6.0.+ for Gradle 8 compatibility and dynamic versions
export const FORGE_BUILD_GRADLE = `plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.+'
}

version = '1.0.0'
group = 'com.yourname.modid' 
archivesBaseName = 'modid'

// Mojang ships Java 17 to end users in 1.18+
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: \${System.getProperty('java.version')} JVM: \${System.getProperty('java.vm.version')} (\${System.getProperty('java.vendor')} \${System.getProperty('java.vm.vendor')})"

minecraft {
    // The mappings can be changed at any time and must be in the following format.
    // Channel:   Version:
    // official   MCVersion             Official field/method names from Mojang mapping files
    // parchment  YYYY.MM.DD-MCVersion  Open community-sourced parameter names and javadocs layered on top of official
    //
    // You must be aware of the Mojang license when using the 'official' or 'parchment' mappings.
    // See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
    mappings channel: 'official', version: project.minecraft_version

    // When true, this property will have all Eclipse/IntelliJ 'run' configurations set to work with the generated
    // sources of your mod, which is needed to run in the dev environment.
    copyIdeResources = true

    // This property enables access transformers for use in development.
    // They will be applied to the JAR the same way as the binary patching.
    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            property 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            property 'forge.logging.console.level', 'debug'

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', 'modid'

            mods {
                modid {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'modid'

            mods {
                modid {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    // Put repositories for dependencies here
    // ForgeGradle automatically adds the Forge maven and Maven Central for you
}

dependencies {
    // Specify the version of Minecraft to use.
    // Any artifact can be supplied so long as it has a "userdev" classifier artifact and is a "zip", "jar", or "tar.gz" object.
    // The "userdev" classifier will be requested and setup by ForgeGradle
    // If the group id is "net.minecraft" and the artifact id is one of ["client", "server", "joined"],
    // then special handling is done to allow a setup of a vanilla dependency without the use of an external repository.
    minecraft "net.minecraftforge:forge:\${project.minecraft_version}-\${project.forge_version}"
}

// Example for how to get properties into the manifest for reading at runtime.
jar {
    manifest {
        attributes([
                "Specification-Title"     : "modid",
                "Specification-Vendor"    : "examplemodsareus",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "examplemodsareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://\${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
`;

export const FORGE_MODS_TOML = `modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/USER/REPO/issues" #optional

[[mods]] #mandatory
modId="modid" #mandatory
version="1.0.0" #mandatory
displayName="Example Mod" #mandatory
displayURL="https://github.com/USER/REPO" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this mod" #optional
authors="Author" #optional
description='''
This is a placeholder description for the mod.
'''
`;

export const FABRIC_MOD_JSON = `{
  "schemaVersion": 1,
  "id": "modid",
  "version": "\${version}",
  "name": "Example Mod",
  "description": "This is an example mod for Fabric.",
  "authors": [
    "Me!"
  ],
  "contact": {
    "homepage": "https://fabricmc.net/",
    "sources": "https://github.com/FabricMC/fabric-example-mod"
  },
  "license": "CC0-1.0",
  "icon": "assets/modid/icon.png",
  "environment": "*",
  "entrypoints": {
    "main": [
      "com.example.mod.ExampleMod"
    ]
  },
  "mixins": [
    "modid.mixins.json"
  ],
  "depends": {
    "fabricloader": ">=0.14.21",
    "minecraft": "~1.20.1",
    "java": ">=17",
    "fabric-api": "*"
  }
}
`;

export const FABRIC_BUILD_GRADLE = `plugins {
	id 'fabric-loom' version '1.4-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:\${project.minecraft_version}"
	mappings "net.fabricmc:yarn:\${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:\${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:\${project.fabric_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	from("LICENSE") {
		rename { "\${it}_\${project.base.archivesName.get()}"}
	}
}
`;

// Explicitly forcing Gradle 8.5 to avoid "Gradle 9.3 not supported" error
export const GITHUB_ACTION_YML = `name: Build Mod

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build with Gradle
        run: gradle clean build
        # Note: We use the system gradle provided by setup-gradle because the wrapper jar is missing in repo

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/libs/*.jar
`;